### ISSUE TITLE
Needs a dope as badge

### ISSUE THREAD

**Issue by bnolan** [Flet/semistandard#10]
Some iteration upon this perhaps?

![semistandard](https://cloud.githubusercontent.com/assets/17499/6894004/34f2c676-d72e-11e4-86d5-a49365679f9f.png)

**Comment by Flet** [comment]
Need more semicolon (mockup):
![semi](https://cloud.githubusercontent.com/assets/360233/6901079/8620df3c-d6d0-11e4-9f7b-83260e39fe32.png)

**Comment by ngoldman** [comment]
SVG mockup using Source Sans Pro with added semicolons to avoid unnecessary dependence on ASI, in case you need it. Using Semibold for the "Semistandard" part. Hope you approve.

![](http://f.cl.ly/items/1g1w3f3G293x043n251j/js-semistandard.svg)

**Comment by bnolan** [comment]
Hah. :P

I like it, but maybe with only the semicolon on the JS. Maybe 'code style' in the same grey as the Semi or is that too light?

**Comment by ngoldman** [comment]
The decision is yours -- I gotta do other stuff now

![](http://f.cl.ly/items/273R433I1Q270E2r2008/js-semistandard-2.svg)

![](http://f.cl.ly/items/140C1v2z2s0e471m3V3q/js-semistandard-3.svg)

Enjoy! :neckbeard:

**Comment by Flet** [comment]
@ngoldman  Thanks!

**Comment by Flet** [comment]
FWIW, I like 
![](http://f.cl.ly/items/273R433I1Q270E2r2008/js-semistandard-2.svg)

**Comment by bnolan** [comment]
I prefer the lighter grey 'code style' but either is good by me!

**Comment by ngoldman** [comment]
[standard](https://github.com/feross/standard#badge) is using my SVG for their badge now too :grin: https://github.com/feross/standard/commit/a39e8c8742a15e7fd845b0c7dd09bfd14309d07f

I will go with what @Flet likes because it is closer to the `standard` one. Will open up a PR.
