### ISSUE TITLE
Support for Web Components? ("HTMLElement" is not defined.)

### ISSUE THREAD

**Issue by homeslicesolutions** [Flet/semistandard#122]
Maybe this is not a valid problem, but I tried running "semistandard" with my Web Component and it doesn't pass because HTMLElement isn't defined.  Is this something semistandard is doing or it's because my version of Node doesn't support webcomponents?

**Comment by Flet** [comment]
By default, `semistandard` (and `standard`) only include the `eslint` environments for `node` and `es6`.

You can add this to your `package.json` to turn on the `browser

**Comment by Flet** [comment]
Its also possible to turn on environments via the command line: 
```bash
semistandard --env browser
```

The list of environments is in eslint's documentation: http://eslint.org/docs/user-guide/configuring#specifying-environments

**Comment by homeslicesolutions** [comment]
Thanks!
