### ISSUE TITLE
Should semistandard-format be removed from semistandard?

### ISSUE THREAD

**Issue by Flet** [Flet/semistandard#151]
With `--fix` added in now, should we remove the `--format` option and instead rely on `--fix`?

`standard` has already done the same thing. The benefit here would be a lot less dependencies to install, resulting in faster installs for folks who include `semistandard` in their devDependencies.

**Comment by Flet** [comment]
@ricardofbarros any thoughts? It feels like `semistandard-format` is not being maintained (and `standard-format` is in a similar state).

**Comment by majgis** [comment]
I just updated and was tripped up by this.  The cli told me about --fix but the readme still referenced semistandard-format.  I'm glad to see the formatter included again, since keeping versions in sync was a pain.

**Comment by Flet** [comment]
OK, `semistandard --format` has been removed in favor of `--fix`.
