### ISSUE TITLE
Removes semicolons on commented lines?

### ISSUE THREAD

**Issue by jsejcksn** [Flet/semistandard#152]
I'm the standard-formatter for Atom ([Atom](https://atom.io/packages/standard-formatter)/[GitHub](https://github.com/stephenkubovic/atom-standard-formatter)) in semi-standard mode, and it is removing semicolons in my commented lines when I actiavte the plugin. I voiced my concern in [an issue in that repo](https://github.com/stephenkubovic/atom-standard-formatter/issues/40#issuecomment-244237097), and was redirected here, so will you take a look at what I'm describing?

**Comment by Flet** [comment]
Hi @jsejcksn,

The formatter included as based off https://github.com/ricardofbarros/semistandard-format which (which is a fork of `standard-format`). Unfortunately its not perfect and not really being maintained.

However, you can now do `semistandard --fix` instead to use the eslint auto-fix function.. I've found it to be a lot more reliable.

**Comment by jsejcksn** [comment]
@Flet I'm not sure what you mean by

> you can now do `semistandard --fix` instead.

If you're talking about terminal commands, I don't use the terminal with Atom.
