### ISSUE TITLE
value used for method call erronously flagged

### ISSUE THREAD

**Issue by baffo32** [Flet/semistandard#166]
```
user@host:~/src/test$ semistandard --version
9.1.0
user@host:~/src/test$ cat bug.js
var promise = new Promise();
promise = promise.then(() => { });
promise = promise.then(() => { });
user@host:~/src/test$ semistandard
semistandard: Semicolons For All! (https://github.com/Flet/semistandard)
  /home/user/src/test/bug.js:1:5: 'promise' is defined but never used.
user@host:~/src/test$ 
```
`promise` is, however, used repeatedly !

**Comment by baffo32** [comment]
After playing around a bit, I discovered it's the last line that matters.  The bug is simply in the line number reported.

**Comment by Flet** [comment]
Thanks for reporting this! However, according to the eslint docs for the [no-unused-vars rule](http://eslint.org/docs/rules/no-unused-vars#rule-details):
>// A read for a modification of itself is not considered as used.
>var z = 0;
>z = z + 1;

**Comment by baffo32** [comment]
Hrm seems to me a method call is more than just a read, as there are side effects.  I guess I'd have to bring it up to eslint.  Thanks.

**Comment by Flet** [comment]
I don't think the above code is vaild as the original promise is never resolved. Also since they are being chained via `then` its not required to reassign it every time:

```js
var promise = Promise.resolve();

promise.then(() => { console.log('hello') });
promise.then(() => { console.log('world') });
```

**Comment by baffo32** [comment]
Well, yes, it was a syntactical example.  Original code was closer to
```
var promise = Promise.resolve();
promise = promise.then((resolve) => { later(() => resolve()) });
if (condition1) promise = promise.then((resolve) => { later2(() => resolve()) });
if (condition2) promise = promise.then((resolve) => { later3(() => resolve()) });
```
The situation being that the content of each line doesn't evaluate until the content of all the above lines has.

**Comment by Flet** [comment]
Ah, even in that example assigning `promise` is probably not needed? ¯\_(ツ)_/¯

**Comment by baffo32** [comment]
I think it is needed to guarantee that the functions are _always_ called in the order `later`, `later1`, `later2`.  Otherwise if `later` is much longer than `later2`, `later3` could win the race against it.

I could move the condition check inside the handler, but I think it becomes much less clear to read.
The eslint error goes away if the last line is changed to not assign `promise`, which is the one place it is not needed, but this may create a bug in the future if somebody adds another line following the pattern and doesn't update the previous one.
