### ISSUE TITLE
Is there something like configuration cascading feature of eslint?

### ISSUE THREAD

**Issue by kt3k** [Flet/semistandard#187]
eslint seems to have configuration cascade feature.
http://eslint.org/docs/user-guide/configuring#configuration-cascading-and-hierarchy

It works like:

> The configuration cascade works by using the closest .eslintrc file to the file being linted as the highest priority, then any configuration files in the parent directory, and so on. When you run ESLint on this project, all files in lib/ will use the .eslintrc file at the root of the project as their configuration. When ESLint traverses into the tests/ directory, it will then use your-project/tests/.eslintrc in addition to your-project/.eslintrc

I'm curious whether semistandard has this (or similar) feature. In our use case, we want to apply `env: ['mocha']` option to only `test/` directory and `env: ['browser']` option to only `browser/` (browser specific directory) etc.

**Comment by Flet** [comment]
`semistandard` uses the `standard-engine` package (just like `standard`) which intentionally ignores .eslintrc files, so this won't work the same way eslint does.

However, there is an `--env` command line switch. So, you could run separate lint commands for each directory:

```
semistandard --env mocha test/**/*.js

semistandard --env browser browser/**/*.js

# fancy glob syntax to include all except test and browser directories
semistandard !(test|browser)/**/*.js

```

Perhaps setting up separate `npm` scripts for each one will work?

**Comment by Flet** [comment]
Oh! one other option is to put this at the top of every test file:

```js
/* eslint-env mocha */
```

And this at the top of every browser file:
```js
/* eslint-env browser */
```

...This would allow for linting everything with a single command.

**Comment by kt3k** [comment]
Thanks for the quick response!

Command line solution seems to work with our use case. Thank you :)
