### ISSUE TITLE
How to ignore files?

### ISSUE THREAD

**Issue by icyflame** [Flet/semistandard#22]
- [standard](https://github.com/feross/standard) provides the `standard.ignore` property inside `package.json` file. I have tried doing that, but semistandard does not ignore the files.

**Comment by icyflame** [comment]
Okay, My bad! The property had to be `semistandard.ignore` ! Thanks, a quick glance at the code in [standard-engine's index.js](https://github.com/Flet/standard-engine/blob/master/index.js#L163) solved the problem!

**Comment by Flet** [comment]
Ah, I'll add this to the README.md as its not obvious. Thanks for the feedback!
