### ISSUE TITLE
Correct way to opt out of certain rules? 

### ISSUE THREAD

**Issue by fxfactorial** [Flet/semistandard#227]
I found https://github.com/Flet/semistandard/issues/111 but still not clear or getting 'it' working. 

invoking with: 

```
$ ./node_modules/.bin/semistandard --verbose  | ./node_modules/.bin/snazzy
```

and in the directory where that command is invoked, I tried having both an `.eslintrc` and a `eslintrc.json` with this config: 

```
{
  "extends": "standard",
    "rules": {
      "camelcase": "off"
    }
}
```

But camel case is still an error. How to proceed? Thank you

**Comment by Flet** [comment]
`semistandard` does not take into account `.eslintrc` or `.eslintrc,.json`. In order to do this, try executing `eslint` directly instead.

**Comment by fxfactorial** [comment]
@Flet Well I would rather not deal with eslint directly at all, the myriad config confuses me. Okay, I guess I will have to write some code to just filter these camel_case rules.

**Comment by Flet** [comment]
If its any help, its possible to disable rules per file by putting this comment at the top of the file:

```
/* eslint-disable camelcase */
var hello_word = true
// no errors

```

**Comment by fxfactorial** [comment]
@Flet ya, it is help. I found that as well, but slight hassle now for new project, but I will do so. worth it, thank you for helping me.

**Comment by Flet** [comment]
@fxfactorial This post inspired me to make something:
https://www.npmjs.com/package/standardx

With this (instead of using semistandard) you should be able to tweak the ruleset via `.eslintrc` or via `eslintConfig` attribute in package.json. 

Just do this for semicolons and snake_case:

In package.json:
```json
"eslintConfig": {
    "rules": {
      "camelcase": 0,
      "semi": [2, "always"],
      "no-extra-semi": 2
    }
  }
```
OR 
via `.eslintrc`
```
{
  "rules": {
    "camelcase": 0,
    "semi": [2, "always"],
    "no-extra-semi": 2
  }
 }
```

**Comment by fxfactorial** [comment]
@Flet Oh dope, just perfect. Thank you!
