### ISSUE TITLE
eslint plugins should be peer dependencies

### ISSUE THREAD

**Issue by timlesallen** [Flet/semistandard#228]
For example, I get this when I've installed semistandard into my project and am calling it in `package.json`:
`Error: Failed to load plugin react: Cannot find module 'eslint-plugin-react'`
This is because it is getting installed in the `node_modules` of `semistandard` and therefore, `eslint` cannot find it.
The correct way to do this would be to specify the `eslint` plugins as [peer depencies](https://nodejs.org/en/blog/npm/peer-dependencies/), not as normal dependencies.
I'd be happy to make a PR for this...

**Comment by timlesallen** [comment]
@Flet If I made a PR for this issue would you merge it? :)

**Comment by lunafi-dorian** [comment]
The "workaround" for that I did is install all of semistandard's dependencies as dev dependencies in the project or on a CI job `cd` into the `node_modules/semistandard` and run `npm i`

**Comment by Flet** [comment]
Hey sorry for leaving you hanging on this. I'm going to close this issue because I don't believe this is an problem with modern versions of node/npm. Feel free to reply if this is still a problem!
