### ISSUE TITLE
Spread operator error

### ISSUE THREAD

**Issue by lakshyaranganath** [Flet/semistandard#23]
```
let oldObject = {
  someString: 'hello world',
  someObj: {
    booleanValue: false,
    someInteger: 5
  }
};
let newObject = { ...oldObject.someObj, someProperty: true };
```
this throws an error in Atom,
`Error: Unexpected token ... at line xx col xx`
this is with `babel-eslint` installed and set as a parser in package.json,
```
"semistandard": {
  "parser": "babel-eslint"
}
```

is there something I'm misunderstanding ?

**Comment by ricardofbarros** [comment]
Seems like the feature of passing custom parsers to semistandard is broken, I tested with standard and everything was okay.

**Comment by Flet** [comment]
thanks for checking @ricardofbarros :) I was just diggging into this too :)

**Comment by Flet** [comment]
OK, I fixed the bug in `standard-engine` that was preventing custom parsers from working. I also merged in the latest `standard` update which allows globals to be added in package.json.

Can you install the latest version of `semistandard` and give it another try? Thanks!

**Comment by ricardofbarros** [comment]
@Flet  It's outputting this:

```
/Users/rbarros/Desktop/github/manager-greeniq/test.js:0:0: Cannot find module 'babel-eslint'
```

Are you looking for the custom parsers on `$PATH`? I have `babel-eslint` installed globally btw.

**Comment by Flet** [comment]
I was getting that issue when I was `npm link`ing things to test locally... a fresh install of `semistandard` globally fixed it. Could this be your issue too, @ricardofbarros

**Comment by ricardofbarros** [comment]
Yes precisely, but I can't install it via npm you need to bump the version first :stuck_out_tongue:

**Comment by Flet** [comment]
the semver for `standard-engine` is `^1.8.1` which means it should pick up the latest... 

For clarity, I bumped `semistandard` to 6.1.2 with the latest `standard-engine` just now :smile:

**Comment by lakshyaranganath** [comment]
it works now thankyou :)

**Comment by Flet** [comment]
Excellent! Thanks for reporting!

**Comment by lakshyaranganath** [comment]
err, the global install and cli tool of semistandard isnt working anymore.

its asking for a babel-eslint module...
do i need to explicitly install babel-eslint globally?

**Comment by ricardofbarros** [comment]
If you are using the cli I think you need to have `babel-eslint` and `eslint` installed globally. 
In the plugin `linter-js-standard` you don't need to have it installed globally because it will get `babel-eslint` from the plugin dependencies.

**Comment by lakshyaranganath** [comment]
Didnt test that, i just installed a local copy since i have babel-eslint already as a parser and im running it through 
`./node_modules/.bin/semistandard`
works :+1:
