### ISSUE TITLE
Cannot read property 'ecmaFeatures' of undefined

### ISSUE THREAD

**Issue by bonesoul** [Flet/semistandard#234]
Getting

Parsing error: Cannot read property 'ecmaFeatures' of undefined

Tell us about your environment

ESLint Version: 5.1.0
Node Version: 10.6.0
**npm Version:**6.1.0"
my eslintrc

env:
  node: true
  es6: true
  jquery: false
  browser: false

extends:
  - eslint:recommended

rules:
  curly: off

**Comment by Flet** [comment]
Hey I just updated this project to eslint 5 (and the latest standard config). This (or `eslint-config-standard`) should work for you now. I'm closing this, but feel free to comment if you're still experiencing problems.

**Comment by Flet** [comment]
e
