### ISSUE TITLE
Parsing error: Cannot find module '@babel/types'

### ISSUE THREAD

**Issue by imakeinterfaces** [Flet/semistandard#235]
When running semistandard with @babel 7 it fails on this error. I have tried installing @babel/types as a dev dependency but it does not work. I assume this is peer dependency problem and I tried running npm install inside of node_modules/@babel-types but this has not worked.

**Comment by imakeinterfaces** [comment]
Looking into this more, i see the problem is for the most part resolved by adding semistandard to package.json `scripts` like so: 
    "semistandard": "semistandard",
    "semistandard::fix": "semistandard --fix",

**Comment by Flet** [comment]
OK, glad you found a workaround. I just updated to the latest version of `eslint` and the latest standard config. Can you give the new version a try?
