### ISSUE TITLE
Travis CI failing with Node 6 and v13.0

### ISSUE THREAD

**Issue by daffl** [Flet/semistandard#237]
This is kind of a strange issue because I can't see anything obvious that changed in the v13.0.0 release but all our Greenkeeper update PRs are failing in Travis CI on Node 6 on the `semistandard --fix` command with:

```
> semistandard --fix
/usr/bin/env: node: No such file or directory
```

[Example](https://travis-ci.org/feathersjs-ecosystem/feathers-authentication-hooks/builds/451206033).

**Comment by daffl** [comment]
Did some more digging and this appears to be a linebreak issue only in Linux and on Node version 6. It is looking for `/usr/bin/env node\r`

**Comment by alpha0010** [comment]
Ran into this as well.  Thought I could fix it in the git repo, but looks like the EOLs are not committed; must be occurring during packaging?

(Updating our OS and node version bypassed the issue.)

**Comment by daffl** [comment]
I think republishing a patch (potentially from a Linux or Mac OS machine) with the latest version of npm may fix this.

**Comment by Flet** [comment]
Strange! I'll try to fix it

**Comment by Flet** [comment]
OK I've republished form Linux. @daffl @alpha0010 can you give it another try with `semistandard@13.0.1`?

**Comment by daffl** [comment]
That definitely did it for us here 🙏
