### ISSUE TITLE
Is there a jsBeautify config for this?

### ISSUE THREAD

**Issue by kirkstrobeck** [Flet/semistandard#31]
This is nearly there ..
```
{
  "brace_style": "collapse",
  "break_chained_methods": false,
  "eval_code": false,
  "indent_char": " ",
  "indent_level": 0,
  "indent_size": 2,
  "indent_with_tabs": false,
  "jslint_happy": true,
  "keep_array_indentation": false,
  "keep_function_indentation": false,
  "max_preserve_newlines": 2,
  "preserve_newlines": true,
  "space_before_conditional": true,
  "unescape_strings": false,
  "wrap_line_length": 0
}
```

**Comment by vaelinn** [comment]
+1 
My current setup cleans up most of the issues that --format does not take care of that do not require altering variables. I just need formatting for the space for generator functions and between the function parenthesis. This would make it much easier to switch a project with alot of code over to using semistandard.

**Comment by Flet** [comment]
The --format command is provided by `semistandard-format` which uses esformatter for formatting. @vaelinn what does your current setup cover that --format misses?

Ideally the --format command should be all we need, but its nice to  have this jsBeautify config too :)

**Comment by vaelinn** [comment]
The two pieces that --format does not do for me are:

1. Inserting a space between asterisks for generator functions
Example:
function* doStuff -> function * doStuff

2. Inserting space between a function name and the first parenthesis
Example:
function doStuff(args) -> funciton doStuff (args)

**Comment by Flet** [comment]
If someone has a full copy of a jsbeautify config I'm happy to accept a PR it to the README (or link to it if its in another repo).
