### ISSUE TITLE
Vim syntastic plugin not reporting errors

### ISSUE THREAD

**Issue by tejasshah93** [Flet/semistandard#32]
Tried adding this line to `.vimrc`

    let g:syntastic_javascript_checkers = ['semistandard']

But it doesn't report errors on saving a .js file in Vim. Am I missing something here?
P.S. `semistandard` is installed globally

**Comment by joshuakarjala** [comment]
I have same issue. Tested with `standard` and it work there but not with `semistandard`

**Comment by joshuakarjala** [comment]
Fixed with:

```
let g:syntastic_javascript_checkers=['standard']
let g:syntastic_javascript_standard_exec = 'semistandard'
```

**Comment by dcousens** [comment]
Awesome @joshuakarjala :+1:

**Comment by tejasshah93** [comment]
@joshuakarjala works perfectly :+1: 

Closing this issue
