### ISSUE TITLE
Display 2-space indentation as if it's 4-space wide

### ISSUE THREAD

**Issue by gsklee** [Flet/semistandard#33]
Is there any way to display 2-space indentations as if it's 4-space wide for common editors (Atom, Sublime, Vim, etc.)?

My team is interested in adapting Semistandard but the enforcement on pure personal preference (ie. indentation) is holding them off. We're looking for a way to introduce Semistandard into our workflow but allowing different indentation depth. Tweaking the width of indentation space character seems to be a way of doing it.

**Comment by Flet** [comment]
I'm not sure of a way to do this unfortunately :( 

Two space indentation is a rule inherited from `standard`, so it's very unlikely to be changed.

However! It's possible to create your own linting CLI tool that is customized to your team's preferences using [standard-engine](https://github.com/Flet/standard-engine). It is all of the guts of `standard` without the config.

First, create an eslint [sharable config](http://eslint.org/docs/developer-guide/shareable-configs). It may be easiest ot just clone to [eslint-config-semistandard](https://github.com/Flet/eslint-config-semistandard) or [eslint-config-standard](https://github.com/feross/eslint-config-standard) (or one of the [many others that exist](https://www.npmjs.com/search?q=eslintconfig)).

Next, create the CLI package itself The `standard-engine` README does a pretty good job of explaining, but again it may be easiest just to clone `semistandard` and change the eslint config.

Publish the CLI package to npm and you're in business!

...All that being said, I'm going to close this issue for now. If you end up creating a new CLI too, send a pull request to `standard-engine` and we will add it to the README! :+1:

**Comment by gsklee** [comment]
@Flet Got it, thanks for the explanation! :+1:

**Comment by wesleytodd** [comment]
Stumbled on this while looking at [`happiness`](https://github.com/JedWatson/happiness) which is like this and standard but with tabs, which are configurable like the coding gods intended :)
