### ISSUE TITLE
usage

### ISSUE THREAD

**Issue by nickdesaulniers** [Flet/semistandard#6]
am I supposed to be able to run this in a top level directory and have it recursively search and test all of my js files?  If I run it from the top level of [this repo](https://github.com/nickdesaulniers/node-nanomsg), I get:
```
➜  nanomsg git:(master) ✗ semistandard
Error: spawn ENOENT
    at errnoException (child_process.js:988:11)
    at Process.ChildProcess._handle.onexit (child_process.js:779:34)
```

**Comment by Flet** [comment]
Hmm I wonder if this is similar to feross/standard#36. Are you running windows? Try upgrading to the latest version of node/npm.

**Comment by nickdesaulniers** [comment]
OSX 10.8.5
```
➜  nanomsg git:(master) ✗ node -v
v0.10.26
```

**Comment by Flet** [comment]
Ah, yeah can you try upgrading to 0.12 node?
