### ISSUE TITLE
Override standard command name

### ISSUE THREAD

**Issue by eush77** [Flet/semistandard#9]
It doesn't mean this style checker is any less “standard” just because someone grabbed a fancier name first.

Checking for `standard` in npm scripts doesn't mean checking for someone else's standard, it means checking for the standard style for the project you're working on.

```diff
     "url": "http://twitter.com/flettre"
   },
   "bin": {
-    "semistandard": "./bin/cmd.js"
+    "standard": "./bin/cmd.js"
   },
   "bugs": {
     "url": "https://github.com/Flet/semistandard/issues"
```

**Comment by Flet** [comment]
I appreciate the notion! Some folks need to switch between linters often (like myself) so having a unique name has technical benefits.
