### ISSUE TITLE
"Missing space before function parameter" Error

### ISSUE THREAD

**Issue by t-moe** [Flet/semistandard#90]
I have the following code:

```
var o = {
  get foo() {
    return 1;
  }
};
console.log(o);
```

running `semistandard -F` on it, gives me:

> semistandard: Semicolons For All! (https://github.com/Flet/semistandard) 
>   /home/timo/FluentFlow/testStandard.js:2:10: Missing space before function parentheses.

That's ok. But if I add that missing space, it will be removed again by the "format option" and the error stays the same.

**Comment by t-moe** [comment]
Probably related to #47.

**Comment by Flet** [comment]
The formatting is not quite ready for prime time. `semistandard-format` is the underlying package, which just adds semicolons to the output of https://github.com/maxogden/standard-format. I believe there is an issue opened for this over there. Feel free to contribute to make `standard-format` better! :)
